cd $PECL_SRC_DIR
wget-retry https://github.com/phalcon/cphalcon/archive/v${EXTENSION_PHALCON_VERSION}.tar.gz
tar -zxvf v${EXTENSION_PHALCON_VERSION}.tar.gz
mv cphalcon-${EXTENSION_PHALCON_VERSION}/build/php7/64bits phalcon-${EXTENSION_PHALCON_VERSION}


TMP_CFLAGS="$PHP_CFLAGS"
TMP_CPPFLAGS="$PHP_CPPFLAGS"
TMP_LDFLAGS="$PHP_LDFLAGS"

PHP_CFLAGS="-O2 -g -fomit-frame-pointer -DPHALCON_RELEASE"
PHP_CPPFLAGS="$PHP_CFLAGS"

ext-pcl phalcon-${EXTENSION_PHALCON_VERSION}

PHP_CFLAGS="$TMP_CFLAGS"
PHP_CPPFLAGS="$TMP_CPPFLAGS"
PHP_LDFLAGS="$TMP_LDFLAGS"
