eval $(docker-machine env bootapp-docker-machine)

type="$1";
subname="";
if [ ! -z "$type" ]; then
    if [ "$type" = "full" ] || [ "$type" = "mini" ] ; then #|| [ "$type" = "extra" ]
        subname="-$type"
    else
        echo "$type not support, full"; # or extra
        exit;
    fi
fi

tagname="yejune/webserver:7.1.12${subname}"

if [ $subname = "-mini" ]; then
    EXTENSIONS="\
        bcmath\
        bz2\
        calendar\
        ctype\
        gettext\
        gmp\
        hash\
        iconv\
        intl\
        pcntl\
        shmop\
        posix\
        \
        pdo\
        pdo_mysql\
        session\
        sockets\
        apcu\
        \
        json\
        yaml\
        dom\
        xml\
        xmlreader\
        xmlwriter\
        simplexml\
        xsl\
        \
        memcached\
        mongodb\
        redis\
        amqp\
        \
        uuid\
        phalcon\
        phar\
        zip\
        \
        tidy\
        tokenizer\
        \
        sodium\
        \
        screwim\
"
elif [ $subname = "-full" ]; then
    EXTENSIONS="\
        bcmath\
        bz2\
        calendar\
        ctype\
        gettext\
        gmp\
        hash\
        iconv\
        intl\
        json\
        pcntl\
        pdo\
        pdo_mysql\
        posix\
        session\
        sockets\
        apcu\
        memcached\
        mongodb\
        redis\
        uuid\
        phalcon\
        phar\
        shmop\
        zip\
        tidy\
        tokenizer\
        snmp\
        dom\
        xml\
        xmlreader\
        xmlwriter\
        simplexml\
        xsl\
        soap\
        yaml\
        \
        xmlrpc\
        exif\
        fileinfo\
        gd\
        imagick\
        ev\
        uv\
        ssh2\
        sodium\
        gearman\
        amqp\
        screwim\
        swoole\
        \
        dba\
        enchant\
        pspell\
        recode\
        wddx\
        sqlite3\
        pdo_pgsql\
        pdo_sqlite\
        pdo_sqlsrv\
        v8js\
        v8\
"
else
    EXTENSIONS="\
        bcmath\
        bz2\
        calendar\
        ctype\
        gettext\
        gmp\
        hash\
        iconv\
        intl\
        pcntl\
        \
        json\
        \
        pdo\
        pdo_mysql\
        posix\
        session\
        sockets\
        apcu\
        memcached\
        mongodb\
        redis\
        uuid\
        phalcon\
        phar\
        shmop\
        zip\
        tidy\
        tokenizer\
        snmp\
        dom\
        xml\
        xmlreader\
        xmlwriter\
        simplexml\
        xsl\
        soap\
        yaml\
        \
        xmlrpc\
        exif\
        fileinfo\
        gd\
        imagick\
        ev\
        uv\
        ssh2\
        sodium\
        gearman\
        amqp\
        screwim\
        swoole\
"
fi

echo $EXTENSIONS;

docker build --no-cache --tag ${tagname} --build-arg BUILD_LOCALE=ko --build-arg BUILD_EXTENSIONS="${EXTENSIONS}" .

docker push ${tagname}